schema_version = "1.0.0"
id = "autopivotbaker"
version = "1.0.0"
name = "Auto Pivot Baker"
tagline = "Pivot baking for game engines"
maintainer = "NRexha"
type = "add-on"
website = "https://github.com/NRexha/AutoPivotBaker"
tags = ["Import-Export", "Game Engine", "Node"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
[permissions]
files = "Export baked meshes and load bundled geometry nodes"