schema_version = "1.0.0"
id = "autopivotbaker"
version = "0.1.0"
name = "Auto Pivot Baker"
tagline = "Bake and export instance pivot data for use in game engines."
maintainer = "NRexha"
type = "add-on"
website = "https://github.com/NRexha"
tags = ["Import-Export", "Node"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]